---
title: "HURT 100 Statistics"
author: "Gary Holton"
date: "2023-01-18"
output: html_document
---

Some statistics regarding the [HURT 100](http://hurt100.com), gleaned from [Ultrasignup](http://ultrasignup.com).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(tidyverse)
library(dplyr)
library(DT)
```

```{r, echo=F, eval=T}
# baseurl <- 'https://ultrasignup.com/results_event.aspx?did='
baseurl <- "https://ultrasignup.com/service/events.svc/results/%s/1/json?_search=false"
dids <- read_csv('hurt_did.csv', col_types = cols(.default = col_character()))

hurt <- data.frame()
for (i in 1:nrow(dids)) {
  row <- dids[i,]
  url <- sprintf(baseurl, URLencode(row$did))  
  doc <- jsonlite::fromJSON(txt=url) 
  if (length(doc) > 1) {
    doc <- mutate(doc, year = row$year)
    hurt <- rbind(hurt,doc)
  }
}
```

```{r, echo=F, eval=F}
hurt<- read.csv('hurt.csv')
```

As of `r format(Sys.Date(),"%Y")`, a total of `r nrow(filter(hurt, age>=60))` geizers 60 years or older have attempted HURT.

```{r, warning=F,message=F }
hurt %>%
  filter(age >= 60) %>%
  group_by(year,gender) %>%
  summarise(n=n()) %>%
  ggplot(aes(x=year,y=n, fill=gender)) + geom_col()  + ggtitle("HURT 100 entrants over age 60, by year and gender") + theme_minimal()
```

Yet only `r nrow(filter(hurt, age>=60, formattime>0))` have finished. Here's a list of those geizers who did it:

```{r}
hurt %>%
  filter(age >= 60, formattime>0) %>%
  mutate(name = paste(firstname,lastname)) %>%
  arrange(lastname) %>%
  select(name,age,gender,time=formattime,state,year) %>%
  datatable(rownames=F, options=list(pageLength=20, dom='t'))
```
Incredibly, several of these geizers have done it more than once, as shown in the `over60` column below.

```{r, message=F}
# participant_ids of geizer completers
ids <- hurt %>%
  filter(age>=60, formattime>0) %>%
  select(participant_id) %>%
  distinct()
geizer_finish <- hurt %>%
  filter(participant_id %in% ids$participant_id, formattime>0) %>%
  mutate(name= paste(firstname,lastname)) %>%
  group_by(participant_id) %>%
  summarise(finishes=n()) 
geizer_over60 <- hurt %>%
  filter(participant_id %in% ids$participant_id, formattime>0, age>=60) %>%
  mutate(name= paste(firstname,lastname)) %>%
  group_by(participant_id) %>%
  summarise(over60=n()) 
geizers <- hurt %>%
  filter(participant_id %in% ids$participant_id) %>%
  mutate(name= paste(firstname,lastname)) %>%
  group_by(participant_id,name) %>%
  summarise(attempts=n()) 
geizers<- cbind(geizers,finishes=geizer_finish$finishes)
geizers<- cbind(geizers,over60=geizer_over60$over60)
geizers %>%
  dplyr::select(name,attempts,finishes,over60) %>%
  arrange(-over60) %>%
  datatable(rownames = F,caption="Number of HURT 100 attempts, total finishes, and finishes over age 60.", options = list(dom='t'))

  
```

